import React, {useLayoutEffect} from 'react'

import './PrivacyPolicy.scss'
import Header from '../Header/Header'

function PrivacyPolicy() {

    useLayoutEffect(() => {
        window.scrollTo(0, 0)
    });

    return (
        <div>
             <Header/>
             <div className="section-content privacy">
                <div className="intro" style={{padding: '5rem 0 1rem 0'}}>
                    <h2 style={{fontWeight: 'bolder'}}>Privacy Policy for Shramista Tech Private Limited</h2>
                </div>
                <div className="textBody">
                    <p>The tyutee Privacy Policy covers how tyutee collects, uses, discloses, transfers, and stores your information. Your privacy is important to tyutee and to ensure that your personal information is secure, tyutee communicates its privacy and security guidelines to tyutee employees and strictly enforces privacy safeguards within the company. Please familiarize yourself with our privacy practices.</p>
                    
                    <p><strong>1.</strong> Collection & Usage of Personal Information Personal information is data that can be used to uniquely identify or contact a single person. You may be asked to provide your personal information anytime you are in contact with tyutee or tyutee affiliates or tyutee authorized business partners (which includes agents, contractors, vendors, licensors, resellers, system integrators, etc.). When you purchase tyutee services, register for utilizing tyutee services, contact tyutee to report service issues, apply for credit, or participate in an online survey, tyutee, its affiliates or authorized business partners may collect various information, including your name, mailing address, phone number, email address, contact preferences, unique device identifier and credit card information. tyutee, its affiliates and its business partners may share this personal information with each other and use it consistent with this Privacy Policy. They may also combine it with other information to provide and improve tyutee’s services, content, and advertising. The personal information tyutee collects allows it to keep you posted on the latest services announcements, services updates and upcoming events. It also helps tyutee to improve its content, and advertising. You can opt out by sending a notice to our return email address at any time. Please note that opting out may impact your ability to use some tyutee services. tyutee may use your personal information to send important notices, such as communications about purchases, changes to the terms, conditions, and policies, your compliance/non-compliance with the terms and conditions of usage of tyutee services, etc. Because this information is important to your interaction with tyutee, you may not opt out of receiving these communications. tyutee may also use personal information for internal purposes such as auditing, data analysis, and research to improve tyutee’s services, and customer communications. If you enter into a sweepstake, contest, or similar promotion tyutee may use the information you provide to administer those programs.</p>
                    
                    <p><strong>2.</strong> Collection & Usage of Non-Personal Information Non-personal information is data in a form that does not permit direct association with any specific individual. tyutee may collect, use, transfer, and disclose non-personal information for any purpose. tyutee may collect information such as unique device identifier, location, details on services usage and the time zone where a tyutee service is used so that tyutee can better understand customer behaviour and improve its services, and advertising. Where applicable, tyutee may collect and review your content to ensure your compliance with the terms and conditions of usage of its services, etc. tyutee also may collect information regarding customer activities on the tyutee website. This information is aggregated and used to provide more useful information to its customers and to understand which parts of the tyutee website, products, and services are of most interest. Aggregated data is considered non-personal information for the purposes of this Privacy Policy. If tyutee combines non-personal information with personal information the combined information will be treated as personal information, as long as it remains combined and will be subject to the policy mentioned in section 1 above.</p>

                    <p><strong>3.</strong> Cookies & Other Technologies tyutee’s website, online services, interactive applications, email messages, and advertisements may use “cookies” and other technologies such as pixel tags and web beacons. These technologies enable tyutee to understand user behaviour, identify which parts of the website the users have visited, and facilitate and measure the effectiveness of advertisements and web searches. tyutee treats information collected by cookies and other technologies as non-personal information. However, to the extent that Internet Protocol (IP) addresses or similar identifiers are considered personal information by local law, tyutee also treats these identifiers as personal information. Similarly, to the extent that non-personal information is combined with personal information, tyutee treats the combined information as personal information for the purposes of this Privacy Policy. tyutee and its partners may also use cookies and other technologies to remember personal information when you use the website, online services, and products/services. The objective in such instances is to make your experience with tyutee more convenient and personal. When you visit the website, tyutee may gather some information automatically and store it in log files. This information includes Internet Protocol (IP) addresses, browser type and language, Internet service provider (ISP), referring and exit pages, operating system, date/time stamp, and clickstream data. tyutee uses this information to understand and analyse trends, to administer the site, to learn about user behaviour on the site, and to gather demographic information about its user base as a whole. tyutee may use this information in its marketing and advertising. In some of its email messages, tyutee may use a “click-through URL” linked to content on the tyutee website. When customers click one of these URLs, they pass through a separate web server before arriving at the destination page on the website. This click-through data is tracked to enable the determination of interest in particular topics and measure the effectiveness of the customer communications. If you prefer not to be tracked in this way, you should not click text or graphic links in the email messages. Pixel tags enable tyutee to send email messages in a format customers can read, and they indicate whether mail has been opened. tyutee may use this information to reduce or eliminate messages sent to customers.</p>

                    <p><strong>4.</strong> Disclosure to Third Parties At times tyutee may make certain personal information available to partners that work with tyutee to provide services, or that help tyutee market to customers. For example, when you purchase tyutee services, you authorize tyutee and its service providers to exchange the information you provide during the activation process to carry out services. If you are approved for services, your account will be governed by tyutee and its service providers’ privacy policies. Personal information will only be used by tyutee to provide or improve its services and advertising; it will not be shared with third parties for their marketing purposes. tyutee shares personal information with partners who provide services such as information processing, extending credit, fulfilling customer orders, managing and enhancing customer data, providing customer service, assessing your interest in tyutee services, and conducting customer research or satisfaction surveys. These companies are obligated to protect your information and may be located wherever tyutee operates. It may be necessary − by law, legal process, litigation, and/or requests from public and governmental authorities within or outside your country of residence − for tyutee to disclose your personal information. tyutee may also disclose information about you if tyutee determines that for purposes of national security, law enforcement, or other issues of public importance, disclosure is necessary or appropriate. tyutee may also disclose relevant information if tyutee determines that disclosure is reasonably necessary to enforce its terms and conditions or protect its operations or users. Additionally, in the event of a reorganization, merger, or sale, tyutee may transfer any and all personal information tyutee collect to the relevant third-party.</p>

                    <p><strong>5.</strong> Protection of Personal Information tyutee takes precautions including administrative, technical, and physical measures to safeguard your personal information against loss, theft, and misuse, as well as against unauthorized access, disclosure, alteration, and destruction. When you use some tyutee services or post on a tyutee forum, chat room, or social networking service, the personal information you share is visible to other users and can be read, collected, or used by them. You are responsible for the personal information you choose to submit in these instances.</p>

                    <p><strong>6.</strong> Integrity and Retention of Personal Information tyutee will continue to expand your ability and make it easy for you to keep your personal information accurate, complete, and up to date. tyutee will retain your personal information for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or prescribed by law.</p>

                    <p><strong>7.</strong> Access to Personal Information For certain services, tyutee requests user personal data such as email address information to complete registration and authenticate you as a valid user . In the future, as additional information is required for renewals or future registrations, tyutee will make good faith efforts to provide you with access so that you can request for tyutee to correct the data if it is inaccurate or delete the data if tyutee is not required to retain it by law or for legitimate business purposes. tyutee may decline to process requests that are unreasonably repetitive, require disproportionate technical effort, jeopardize the privacy of others, are extremely impractical, or for which access is not otherwise required by local law.</p>

                    <p><strong>8.</strong> Third-Party Sites and Services tyutee websites and services may contain links to third-party websites, products, and services. tyutee and services may reference other sites offered by third parties. Information collected by third parties, which may include additional information or requirements, is governed by their respective privacy practices. tyutee encourages you to learn about the privacy practices of those third parties.</p>
                </div>
            </div>
        </div>
        
    )
}

export default PrivacyPolicy
